name: dagger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agent:
    name: agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        id: test
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.16"
          verb: call
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Fix
        id: fix
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.16"
          verb: call
          args: fix --repository=$GITHUB_REPOSITORY --ref=$GITHUB_REF_NAME --token=env://GITHUB_API_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: "gpt-4o"
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        if: ${{ always() &&  github.event_name == 'pull_request' && steps.test.conclusion == 'failure' }}
